[
  {
    id: "cs_test_a1k2joHfpkIdoBurasSHVLsPEqlpFIBtXG0Fqs8JBqghvXB9DCOzgxpNV0",
    object: "checkout.session",
    after_expiration: null,
    allow_promotion_codes: null,
    amount_subtotal: 300,
    amount_total: 300,
    automatic_tax: { enabled: false, status: null },
    billing_address_collection: null,
    cancel_url: "https://example.com/cancel",
    client_reference_id: null,
    client_secret: null,
    consent: null,
    consent_collection: null,
    created: 1701498992,
    currency: "usd",
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      shipping_address: null,
      submit: null,
      terms_of_service_acceptance: null,
    },
    customer: "cus_P6jmD7zLVxIswv",
    customer_creation: null,
    customer_details: {
      address: {
        city: null,
        country: "GE",
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      email: "losaberidze777@gmail.com",
      name: "242424",
      phone: null,
      tax_exempt: "none",
      tax_ids: [],
    },
    customer_email: null,
    expires_at: 1701585392,
    invoice: null,
    invoice_creation: {
      enabled: false,
      invoice_data: {
        account_tax_ids: null,
        custom_fields: null,
        description: null,
        footer: null,
        metadata: {},
        rendering_options: null,
      },
    },
    livemode: false,
    locale: null,
    metadata: {},
    mode: "payment",
    payment_intent: "pi_3OImonE7glB9R79n0KuXX2Rn",
    payment_link: null,
    payment_method_collection: "if_required",
    payment_method_configuration_details: null,
    payment_method_options: {},
    payment_method_types: ["card"],
    payment_status: "paid",
    phone_number_collection: { enabled: false },
    recovered_from: null,
    setup_intent: null,
    shipping_address_collection: null,
    shipping_cost: null,
    shipping_details: null,
    shipping_options: [],
    status: "complete",
    submit_type: null,
    subscription: null,
    success_url: "https://youtube.com/",
    total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
    ui_mode: "hosted",
    url: null,
  },
];
